Map('', '<C-d>', '6+zz')
Map('', '<C-u>', '6-zz')
Map('', '<C-f>', '10+zz')
Map('', '<C-b>', '10-zz')
Map('', '"', ':')
Map('', "'", '"')
Map('', ':', ',')
Map('', ',s', '/\\V')
Map('', ',S', '?\\V')
Map('', '/', '/\\v')
Map('', '?', '?\\v')
Map('', 'zp', ']p')
Map('', 'zP', ']P')
Map('', 'gM', 'M')

Map({ 'n', 'v' }, '`', '@')
Map({ 'n', 'v' }, '``', '@@')

Map('v', 'u', '<Esc>u')
Map('v', '&', ':s`\\V')

Map('i', '<C-l>', '<C-x><C-l>')
Map('i', '<C-k>', '<C-o>O')
Map('i', '<C-j>', '<C-o>o')

Map('o', '{', 'V{')
Map('o', '}', 'V}')
Map('o', '+', 'v+')
Map('o', '-', 'v-')

Map('n', '<C-k>', 'O<Esc>')
Map('n', '<C-j>', 'o<Esc>')
Map('n', 'R', 'q')
Map('n', 'gK', 'K')
Map('n', 'Y', 'yg_')
Map('n', '~', '~h')
Map('n', 'dp', 'ddp')
Map('n', 'dP', 'ddkP')
Map('n', 'yp', 'yyp')
Map('n', 'yP', 'yyP')
Map('n', '&', ':%s`\\V')
Map('n', '<M-w>', 'ZZ')

-- Vertical movement
Map('v', '_', '-')
Map('n', '_', '-')
Map('n', '<leader>k', 'kg_')
Map('v', '<leader>k', 'kg_')
Map('n', '<leader>j', 'jg_')
Map('v', '<leader>j', 'jg_')

-- Map('t', '<M-H>', [[<C-\><C-N><C-w>h]])
-- Map('t', '<M-J>', [[<C-\><C-N><C-w>j]])
-- Map('t', '<M-K>', [[<C-\><C-N><C-w>k]])
-- Map('t', '<M-L>', [[<C-\><C-N><C-w>l]])
